### ISSUE TITLE
"Pre-requisite software" not listed anywhere

### ISSUE THREAD

**Issue by jvollme** [avsastry/modulome-workflow#11]
Your READ.Me states that all "Pre-requisite software" required for using the workflows without docker is listed under each respective workflow.
However no such list is then given anywhere. All simply refer to your docker. 
Could you please provide a list of dependencies for installing this WITHOUT using docker?

**Comment by jvollme** [comment]
furthermore: Your docker file itself seems to use conda to install dependencies (but also not a full list, it seems, because i can't find entrez on the list there). So wouldn't it be simpler to just provide a conda-recipe instead of a docker container?

**Comment by avsastry** [comment]
My bad, I must have forgotten to add the conda files. I'll get those up soon.

Also, there is a separate docker file for the entrez step (step 1) and the rest of the steps, specifically because the entrez container is very finicky and doesn't work well with other tools. I'll make this clearer in the README

**Comment by avsastry** [comment]
Ok, I've added an environment.yaml file that should make it easy to install through conda. This will work for everything except step 5.

Step 5 uses pymodulon, which has an outdated conda environment (uses `jupyter` conda package rather than `notebook`, which causes issues). For now, please run `conda install -c conda-forge pymodulon` to get the pymodulon environment for Step 5. I'll fix this soon.
